### ISSUE TITLE
cancellare un allegato dopo la sua acquisizione

### ISSUE THREAD

**Issue by pachiara** [pachiara/alice#108]
Paperclip scrive i file caricati in una specie di cache situata in public/system/detections/xmls/.
Occorre cancellare i file dopo la loro acquisizione altrimenti diventa enorme lo spazio disco occupato inutilmente.
https://github.com/thoughtbot/paperclip#deleting-an-attachment
Deleting an Attachment
Set the attribute to nil and save.

@user.avatar = nil
@user.save

**Comment by EnzoFerri** [comment]
Il fatto che nel model della detection fosse specificato  has_attached_file :xml, faceva sì che, cancellando  l'xml caricato, si ottenessero poi errori applicativi per la mancanza dell'attachment.
La soluzione è stata la riscrittura di tutta la procedura di upload, senza più l'utilizzo della gemma paperclip.
I dati statistici utili relativi ai precedenti caricamenti sono stati migrati in due campi valorizzati ora nel metodo di caricamento del file all'interno della classe Detection.
